### ISSUE TITLE
Cannot read property 'NavigationType' of undefined

### ISSUE THREAD

**Issue by dzpt** [archriss/react-native-display-html#2]
Got this error after installing package.
Couldn't run.

The error is line 50 of file: node_modules/react-native-webview-bridge/webview-bridge/index.ios.js

**Comment by Exilz** [comment]
Hi,
the plugin has a strong dependency on [react-native-webview-bridge](https://github.com/archriss/react-native-webview-bridge).

The original webview component in react-native's core is still quite buggy, hence the need for this custom one.

You need to install it as a native dependency. I completely forgot about this in the readme.

Please tell me if this fixed it for you.

**Comment by vagnerSl** [comment]
+1

**Comment by Exilz** [comment]
@vagnerSl have you tried installing (linking too) react-native-webview-bridge ?

**Comment by vagnerSl** [comment]
yes.

**Comment by Exilz** [comment]
Well... that's weird, because it means `RCTWebViewBridgeManager` which is the native component you've linked couldn't be found.

Can you try using this commit in your `package.json` ?

`"react-native-webview-bridge": "git://github.com/archriss/react-native-webview-bridge.git#36a74a6"`

The original repo must have changed or something.
