### ISSUE TITLE
onMessage not called

### ISSUE THREAD

**Issue by vvusts** [archriss/react-native-display-html#6]
This is my setup:
```
<DisplayHTML
               onMessage={(event)=> console.log('test...') }
                allowUniversalAccessFromFileURLs={true}
                allowFileAccess={true}
                ref={html => (this.htmlView = html)}
                key={this.props.key}
                htmlString={this.props.description}
                ...
```
I also installed react-native-webview-bridge.
But onMessage is never called.
What can be reason for that?

Version 1.2.3

**Comment by vvusts** [comment]
This is probably the worst approach but I changed library code.
I passed as props another function and used it in onMessage function:
```
const { additionalHeight, onMessage, onChange } = this.props;
...
this.setState({ height: newHeight });
            if (onChange) {
                onChange(newHeight);
            }
```
This works.
If you have any suggestion please?

**Comment by Exilz** [comment]
Hi,
if you look in the source [here](https://github.com/archriss/react-native-display-html/blob/master/index.js#L130-L139) you can see that I only call the `onMessage` prop when eventData *doesn't* have any `height` key in it.

The logic behind this behavior is to let the library handle the resizing by itself, only calling the user's `onMessage` prop when anything else comes from the webview.

If you want to, let's say open a link that has been clicked into the webview inside your react-native app, you might add a listener in the webview that would dispatch something like this 

```javascript
window.WebViewBridge.send(JSON.stringify({ href: href }));
```

Since `eventData` will only have the `href` key, your `onMessage` prop will be called and you'll be free to do whatever you want with this data.

Hope this helps

**Comment by vvusts** [comment]
Hi, thanks for feedback.
So onMessage is not intended to be called whenever content change?
I need to know whenever content change it's height so parent component can be informed about that.
Then update that I added was actually the only solution to get that info from component.

**Comment by Exilz** [comment]
Well, the script injected in your webview sets an interval to check for height changes. So if your content updates, it will scale appropriately within 1 second.

However, this plugin, in its current state, doesn't give you access to the `height` value, it's all handled within the plugin.

If I understand correctly, you need to access this height to apply some kind of specific styling to the parent of your webview ? Are you sure you really need to do that ?

**Comment by vvusts** [comment]
I actually can access to component height by `this.displayHtml.state.height`
but when this is changes parent is not updated.

My use case is if content is more that 100px I show button otherwise I don't show it.
With update that I made I am now able to do that.

Maybe it can be good idea to implement in this plugin actually it is expand collapse button if content is more than defined height.

**Comment by Exilz** [comment]
This is an interesting idea. At the very least, we should change the plugin so that people are able to access the height dynamically if they want to implement something similar by themselves.
